# Generated by Django 5.1.5 on 2025-04-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("former-colleague", "Former Colleague"),
                            ("current-colleague", "Current Colleague"),
                            ("classmate", "Classmate"),
                            ("friend", "Friend"),
                            ("mentor", "Mentor"),
                            ("recruiter", "Recruiter"),
                            ("manager", "Manager"),
                            ("industry-contact", "Industry Contact"),
                            ("other", "Other"),
                        ],
                        default="industry-contact",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("last_contacted", models.DateField(blank=True, null=True)),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("avatar", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("call", "Call"),
                            ("meeting", "Meeting"),
                            ("message", "Message"),
                            ("other", "Other"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="contacts.contact",
                    ),
                ),
            ],
        ),
    ]
