# Generated by Django 5.1.5 on 2025-04-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_user_alter_contact_relationship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
