# Generated by Django 5.1.5 on 2025-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contact_is_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["contact", "-date"], name="contacts_in_contact_05aab5_idx"
            ),
        ),
    ]
