"""
Django settings for cover_backend project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from corsheaders.defaults import default_methods

import environ

BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY
SECRET_KEY = env("SECRET_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

COVER_LETTER_PROMPT = env("COVER_LETTER_PROMPT")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "ai-cover-letter-generator-i2xa.onrender.com",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "social_django",  # For third-party OAUTH
    "storages",
    "accounts",  # Added accounts app here
    "corsheaders",
    "AI_generator",
    "job_applications",
    # "debug_toolbar",
    # "silk",
]

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"  # required for collectstatic
MEDIA_URL = "media/"
# new
INTERNAL_IPS = ["127.0.0.1"]

# authentication Backends
AUTHENTICATION_BACKENDS = [
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    # new middleware -> silk
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    # "debug_toolbar.middleware.DebugToolbarMiddleware",  # new
    # "silk.middleware.SilkyMiddleware",
]


# silk config

# SILKY_PYTHON_PROFILER = True  # Enables Python function-level profiling
# # SILKY_PYTHON_PROFILER_BINARY = True  # Stores binary .prof files
# SILKY_AUTHENTICATION = False  # Use your auth system
# SILKY_AUTHORISATION = False  # Use your permission system


ROOT_URLCONF = "cover_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cover_backend.wsgi.application"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.db.backends": {
            "level": "DEBUG",  # Log all SQL
            "handlers": ["console"],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("DATABASE_NAME", "postgres"),
#         "USER": os.getenv("DATABASE_USER", "postgres"),
#         "PASSWORD": os.getenv("DATABASE_PASSWORD", "password"),
#         "HOST": os.getenv("DATABASE_HOST", "localhost"),
#         "PORT": os.getenv("DATABASE_PORT", "5432"),
#     }
# }

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ["PGDATABASE"],
#         "USER": os.environ["PGUSER"],
#         "PASSWORD": os.environ["PGPASSWORD"],
#         "HOST": os.environ["PGHOST"],
#         "PORT": os.environ["PGPORT"],
#     }
# }
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ["DATABASE_NAME"],
#         "USER": os.environ["DATABASE_USER"],
#         "PASSWORD": os.environ["DATABASE_PASSWORD"],
#         "HOST": os.environ["DATABASE_HOST"],
#         "PORT": os.environ["DATABASE_PORT"],
#     }
# }
# new for logging
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {"class": "logging.StreamHandler"},
#     },
#     "loggers": {
#         "django.db.backends": {
#             "level": "DEBUG",
#             "handlers": ["console"],
#         },
#     },
# }


# prod
DATABASES = {
    "default": dj_database_url.config(
        default=env("DATABASE_URL"), conn_max_age=600, ssl_require=True
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SOCIAL_AUTH_PIPELINE = [
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#
# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
#
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True

#
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SECURE = False  # SET TO TRUE IN PRODUCTION
# SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = False  # set to true in prod
CSRF_COOKIE_HTTPONLY = False
# CSRF_USE_SESSIONS = False
CSRF_USE_SESSIONS = False

# CORS_ALLOW_HEADERS = [
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# ]
# LOGIN_URL = "/google/login/google-oauth2/"
# SESSION_COOKIE_SAMESITE = "Lax"


if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }

# prev with s3
# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#     },
#     "staticfiles": {
#         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#     },
# }
#
# cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # Change the URL if your Redis is hosted elsewhere
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


AUTH_USER_MODEL = "accounts.CustomUser"
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True
# ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5173",
    "https://ai-cover-letter-generator-i2xa.onrender.com",
    "https://ai-cover-letter-generator-mrxj.vercel.app",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5173",
    "https://ai-cover-letter-generator-i2xa.onrender.com",
    "https://ai-cover-letter-generator-mrxj.vercel.app",
]
# CORS_ALLOW_METHODS = (*default_methods,)
SESSION_COOKIE_SAMESITE = "Lax"
# CSRF_COOKIE_SAMESITE = "None"
# CSRF_COOKIE_DOMAIN = "ai-cover-letter-generator-i2xa.onrender.com"

# CSRF_COOKIE_SAMESITE = None  # For cross-origin requests
# CSRF_COOKIE_PATH = "/"
# CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]
# CSRF_COOKIE_SECURE = True

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = env("SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI")
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ["email", "profile", "openid"]
SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = "us-east-2"  # Change if needed
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
print("custom AWS_S3_CUSTOM_DOMAIN", AWS_S3_CUSTOM_DOMAIN)
print("AWS_STORAGE_BUCKET_NAME", AWS_STORAGE_BUCKET_NAME)
print("secret", AWS_SECRET_ACCESS_KEY)
print("access", AWS_ACCESS_KEY_ID)
AWS_S3_FILE_OVERWRITE = False

# Use S3 as default storage for files
# Redirect URLs
# LOGIN_REDIRECT_URL = "/"
# LOGOUT_REDIRECT_URL = "/"
GEMINI_API_KEY = env("GEMINI_API_KEY")
