# Generated by Django 5.1.5 on 2025-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
