# Generated by Django 5.1.5 on 2025-04-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0002_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="company",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="position",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
