# Generated by Django 5.1.5 on 2025-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0003_alter_jobapplication_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="location",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
