# Generated by Django 5.1.5 on 2025-04-06 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0004_alter_jobapplication_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "position"], name="job_applica_status_076d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "company"], name="job_applica_status_06ab98_idx"
            ),
        ),
    ]
