# Generated by Django 5.1.5 on 2025-04-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_applications",
            "0005_jobapplication_job_applica_status_076d4f_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobapplication",
            name="job_applica_status_076d4f_idx",
        ),
        migrations.RemoveIndex(
            model_name="jobapplication",
            name="job_applica_status_06ab98_idx",
        ),
    ]
