# Generated by Django 5.1.5 on 2025-04-06 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_applications",
            "0006_remove_jobapplication_job_applica_status_076d4f_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "-date_applied", "-id"], name="idx_user_date_id"
            ),
        ),
    ]
