# Generated by Django 5.1.5 on 2025-04-06 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0007_jobapplication_idx_user_date_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobapplication",
            name="idx_user_date_id",
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["date_applied", "id"], name="job_applica_date_ap_8e7ec8_idx"
            ),
        ),
    ]
