# Generated by Django 5.1.5 on 2025-04-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0008_remove_jobapplication_idx_user_date_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobapplication",
            name="job_applica_date_ap_8e7ec8_idx",
        ),
    ]
