# Generated by Django 5.1.5 on 2025-04-06 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0010_jobapplication_job_applica_date_ap_787055_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "-date_applied", "-id"],
                name="job_applica_status_ba7945_idx",
            ),
        ),
    ]
