# Generated by Django 5.1.5 on 2025-04-07 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0011_jobapplication_job_applica_status_ba7945_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobapplication",
            name="job_applica_date_ap_787055_idx",
        ),
        migrations.RemoveIndex(
            model_name="jobapplication",
            name="job_applica_status_ba7945_idx",
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "-date_applied", "-id"],
                name="job_applica_user_id_50fc4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "status", "-date_applied", "-id"],
                name="job_applica_user_id_982a2c_idx",
            ),
        ),
    ]
