# Generated by Django 5.1.5 on 2025-04-07 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_applications",
            "0012_remove_jobapplication_job_applica_date_ap_787055_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "status", "position", "-date_applied", "-id"],
                name="job_applica_user_id_cdca4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "status", "company", "-date_applied", "-id"],
                name="job_applica_user_id_d10cc0_idx",
            ),
        ),
    ]
