# Generated by Django 5.1.5 on 2025-04-07 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0014_jobapplication_job_applica_user_id_d4ca4f_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobapplication",
            name="job_applica_user_id_d4ca4f_idx",
        ),
    ]
