# Generated by Django 5.1.5 on 2025-04-21 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_applications",
            "0015_remove_jobapplication_job_applica_user_id_d4ca4f_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="date_applied",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "company", "-date_applied", "-id"],
                name="job_applica_user_id_64be69_idx",
            ),
        ),
    ]
