# Generated by Django 5.1.5 on 2025-02-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_generator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverletter",
            name="cover_letter_file",
        ),
        migrations.AddField(
            model_name="coverletter",
            name="cover_letter_file_path",
            field=models.CharField(
                default="cover_letters/default.pdf", max_length=1024
            ),
            preserve_default=False,
        ),
    ]
